# Generated by Django 3.0.8 on 2020-07-01 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homepage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_pic', models.ImageField(upload_to='img/profile/%Y/%m/')),
            ],
        ),
    ]
