# Generated by Django 3.0.8 on 2020-07-01 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_homepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='banner_pic',
            field=models.ImageField(upload_to='static/assets/homepage/%Y/%m/'),
        ),
    ]
