# Generated by Django 3.0.8 on 2020-07-01 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20200701_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='banner_pic',
            field=models.ImageField(upload_to='polls/static/assets/homepage/%Y/%m/'),
        ),
    ]
