# Generated by Django 3.0.8 on 2020-07-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20200702_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='button_link',
            field=models.CharField(default='/', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='button_text',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='banner_pic',
            field=models.ImageField(height_field=1200, upload_to='polls/static/assets/homepage/', width_field=500),
        ),
    ]
