# Generated by Django 3.0.8 on 2020-07-02 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20200702_0936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='button_link',
            new_name='banner_button_link',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='button_text',
            new_name='banner_button_text',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='title',
            new_name='banner_title',
        ),
    ]
