# Generated by Django 3.0.8 on 2020-07-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20200702_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='banner_pic',
            field=models.ImageField(upload_to='polls/static/assets/homepage/'),
        ),
    ]
